version: '3.8'
services:
  postgres-db:
    image: postgres:15.0
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: testdb
    networks:
      - my-app-network
networks:
  my-app-network:
    driver: bridge

# docker-compose -f ./docker-compose.yml up -d postgres-db